import type { Metadata } from "next";
import { Poppins, Syne } from "next/font/google";
import "./globals.css";
import Header from "@/sections/Header";
import { ThemeProvider } from "@/components/theme-provider";
import Footer from "@/sections/Footer";

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});
const syne = Syne({
  subsets: ["latin"],
  variable: "--font-oswald",
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "SAMA Nextgen Private Limited",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body
        suppressHydrationWarning
        className={`${poppins.variable} ${syne.variable} antialiased bg-gradient-to-tr from-white h-full to-blue-100 flex flex-col font-poppins min-h-screen text-blue-950 dark:bg-gradient-to-tr dark:from-[#02010A] dark:to-[#04052E] dark:text-white overflow-clip`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <div className=" absolute inset-0 h-screen  overflow-x-clip opacity-100 -z-10">
            <div className="absolute inset-0 size-[620px] border top-2/3 left-40 -translate-x-1/2 -translate-y-1/2 border-blue-500/10 dark:border-blue-500/5 rounded-full shadow-[0_0_80px_inset] shadow-blue-500/10 dark:shadow-blue-500/5"></div>
            <div className="absolute inset-0 size-[820px] border top-2/3  left-40 -translate-x-1/2 -translate-y-1/2 border-blue-500/10 dark:border-blue-500/5 rounded-full shadow-[0_0_80px_inset] shadow-blue-500/10 dark:shadow-blue-500/5"></div>
            <div className="absolute inset-0 size-[1020px] border top-2/3  left-40 -translate-x-1/2 -translate-y-1/2 border-blue-500/10 dark:border-blue-500/5 rounded-full shadow-[0_0_80px_inset] shadow-blue-500/10 dark:shadow-blue-500/5"></div>
            <div className="absolute inset-0 size-[1220px] border top-2/3  left-40 -translate-x-1/2 -translate-y-1/2 border-blue-500/10 dark:border-blue-500/5 rounded-full shadow-[0_0_80px_inset] shadow-blue-500/10 dark:shadow-blue-500/5"></div>
            <div className="absolute inset-0 size-[1420px] border top-2/3  left-40 -translate-x-1/2 -translate-y-1/2 border-blue-500/10 dark:border-blue-500/5 rounded-full shadow-[0_0_80px_inset] shadow-blue-500/10 dark:shadow-blue-500/5"></div>

            <div className="absolute  size-[1100px] bg-gradient-to-tl from-blue-300 to-transparent dark:bg-gradient-to-tl dark:from-blue-800/55  dark:to-transparent -bottom-0 -right-[500px]  blur-3xl rounded-full"></div>
          </div>
          {/* <div className="fixed bottom-4 flex items-center justify-center right-4 z-[1000] size-16 rounded-full bg-white">
            <div className="text-black sm:hidden">vsm</div>
            <div className="text-black max-sm:hidden md:hidden">sm</div>
            <div className="text-black max-md:hidden lg:hidden">md</div>
            <div className="text-black max-lg:hidden xl:hidden">lg</div>
            <div className="text-black max-xl:hidden ">xl</div>
          </div> */}
          <Header></Header>
          <div className=" flex-1">{children}</div>
          <div className="place-content-end mt-auto">
            <Footer></Footer>
          </div>
        </ThemeProvider>
      </body>
    </html>
    // <html lang="en">
    //   <body
    //     suppressHydrationWarning
    //     className={`${poppins.variable} ${syne.variable} antialiased bg-gradient-to-tr from-[#02010A] to-[#04052E] font-poppins min-h-screen text-white `}
    //   >
    //     <div className=" absolute inset-0 h-screen overflow-x-clip opacity-100 -z-10">
    //       <div className="absolute inset-0 size-[620px] border top-2/3 left-40 -translate-x-1/2 -translate-y-1/2 border-blue-500/5 rounded-full shadow-[0_0_80px_inset] shadow-blue-500/5"></div>
    //       <div className="absolute inset-0 size-[820px] border top-2/3  left-40 -translate-x-1/2 -translate-y-1/2 border-blue-500/5 rounded-full shadow-[0_0_80px_inset] shadow-blue-500/5"></div>
    //       <div className="absolute inset-0 size-[1020px] border top-2/3  left-40 -translate-x-1/2 -translate-y-1/2 border-blue-500/5 rounded-full shadow-[0_0_80px_inset] shadow-blue-500/5"></div>
    //       <div className="absolute inset-0 size-[1220px] border top-2/3  left-40 -translate-x-1/2 -translate-y-1/2 border-blue-500/5 rounded-full shadow-[0_0_80px_inset] shadow-blue-500/5"></div>
    //       <div className="absolute inset-0 size-[1420px] border top-2/3  left-40 -translate-x-1/2 -translate-y-1/2 border-blue-500/5 rounded-full shadow-[0_0_80px_inset] shadow-blue-500/5"></div>
    //       <div className="absolute  size-[1100px] bg-gradient-to-tl from-blue-800 to-transparent -bottom-2/3 -right-[500px]  blur-3xl rounded-full"></div>
    //     </div>
    //     <Header></Header>
    //     {children}
    //   </body>
    // </html>
  );
}
